In [1]:
########part a########
import numpy as np  

with open('yelp_labelled.txt') as f1, open('amazon_cells_labelled.txt') as f2, open('imdb_labelled.txt') as f3:
    mylist1 = [line.rstrip('\n') for line in f1]
    mylist2 = [line.rstrip('\n') for line in f2]
    mylist3 = [line.rstrip('\n') for line in f3]
mylist1 = np.array(mylist1)  
mylist2 = np.array(mylist2)  
mylist3 = np.array(mylist3)  

count1 = []
for item in mylist1:
    count1 += item[-1]
print(count1.count('0')) 
print(count1.count('1'))    
  
count2 = []
for item in mylist2:
    count2 += item[-1]
print(count2.count('0')) 
print(count2.count('1')) 
    
count3 = []
for item in mylist3:
    count3 += item[-1]
print(count3.count('0')) 
print(count3.count('1')) 
 

500
500
500
500
500
500


In [2]:
########part c########
ylp_zero = []    
ylp_one = []    
for item in mylist1:
    if int(item[-1]) == 0:
        ylp_zero.append(item)
    else:
        ylp_one.append(item)
            
amz_zero = []    
amz_one = []    
for item in mylist2:
    if int(item[-1]) == 0:
        amz_zero.append(item)
    else:
        amz_one.append(item)
         
imbd_zero = []    
imbd_one = []    
for item in mylist3:
    if int(item[-1]) == 0:
        imbd_zero.append(item)
    else:
        imbd_one.append(item)
        
training = [0 for i in range(400)]*6
testing = [0 for i in range(100)]*6

for i in range(400):
    training[i] = ylp_zero[i]
    training[i + 400] = ylp_one[i]
    training[i + 800] = amz_zero[i]
    training[i + 1200] = amz_one[i]
    training[i + 1600] = imbd_zero[i]
    training[i + 2000] = imbd_one[i]
    
for i in range(100):
    testing[i] = ylp_zero[i + 400]
    testing[i + 100] = ylp_one[i + 400]
    testing[i + 200] = amz_zero[i + 400]
    testing[i + 300] = amz_one[i + 400]
    testing[i + 400] = imbd_zero[i + 400]
    testing[i + 500] = imbd_one[i + 400]
    

In [32]:
########part d########
from nltk.stem import WordNetLemmatizer
from nltk import corpus
import string

wnl = WordNetLemmatizer()
def lemmatize(word):
    for wd_tp in ['a', 's', 'r', 'n', 'v']:
        lemmatize_word = wnl.lemmatize(word,wd_tp)
        if word != lemmatize_word:
            word = lemmatize_word
            break
    return word

In [47]:
########part d########
import nltk
nltk.download('wordnet')
nltk.download('stopwords') 
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import wordnet as wn
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

training_tmp = [sub[ : -2:] for sub in training] 
testing_tmp = [sub[ : -2:] for sub in testing]     

f = []
for i in range(len(training_tmp)):
    ff = []
    s = training_tmp[i]
    s1 = s.lower()
    s2 = s1.translate(str.maketrans('', '', string.punctuation))
    s3 = s2.split( )
    for w in s3:
        if w not in stop_words:
            ff.append(w)
    f.append(ff)
   
w_vct = []  
for i in range(len(f)):
    t = []
    t1 = f[i]
    for wd in t1:
        t2 = lemmatize(wd)
        t.append(t2)
    w_vct.append(t)       
    
strp_nb = []
for i in range(len(w_vct)):
    u = []
    u1 = w_vct[i]
    for wd in u1:
        check_nb = wd.isdigit()
        if check_nb is False:
            u.append(wd)      
    strp_nb.append(u)

ft_vct = []
for i in range(len(strp_nb)):
    for item in strp_nb[i]:
        if item not in ft_vct:
            ft_vct.append(item)
                   
###################################
f_test = []
for i in range(len(testing_tmp)):
    ff = []
    s = testing_tmp[i]
    s1 = s.lower()
    s2 = s1.translate(str.maketrans('', '', string.punctuation))
    s3 = s2.split( )
    for w in s3:
        if w not in stop_words:
            ff.append(w)
    f_test.append(ff)

w_vct_test = []  
for i in range(len(f_test)):
    t = []
    t1 = f_test[i]
    for wd in t1:
        t2 = lemmatize(wd)
        t.append(t2)
    w_vct_test.append(t)    

strp_nb_test = []
for i in range(len(w_vct_test)):
    u = []
    u1 = w_vct_test[i]
    for wd in u1:
        check_nb = wd.isdigit()
        if check_nb is False:
            u.append(wd)      
    strp_nb_test.append(u) 
        
m = [[0 for j in range(len(ft_vct))] for i in range(len(strp_nb))]   
m_test = [[0 for j in range(len(ft_vct))] for i in range(len(strp_nb_test))]

for i in range(len(strp_nb)):
    y = strp_nb[i]
    for item in y:
        idx = ft_vct.index(item)
        ct = y.count(item)
        m[i][idx] = ct

for i in range(len(strp_nb_test)):
    y = strp_nb_test[i]
    for item in y:
        if item in ft_vct:
            idx = ft_vct.index(item)
            ct = y.count(item)
            m_test[i][idx] = ct

            

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/zeyuwang/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/zeyuwang/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [107]:
print(m[10])
print(m[10].count(1))
print(m[11])
print(m[11].count(1))

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [108]:
print(len(m[10]))

3736


In [48]:
########part e########
import math

norm_list = []
for i in range(len(strp_nb)):
    sum_square = 0
    for j in range(len(ft_vct)):
        sum_square = sum_square + (m[i][j])**2
    sqrd = math.sqrt(sum_square)
    norm_list.append(sqrd)

normed_m = []   
for i in range(len(strp_nb)):
    if all(v == 0 for v in m[i]):
        normed = m[i]
    else:
        normed = [x / float(norm_list[i]) for x in m[i]]
    normed_m.append(normed)    
                
norm_list_test = []
for i in range(len(strp_nb_test)):
    sum_square = 0
    for j in range(len(ft_vct)):
        sum_square = sum_square + (m_test[i][j])**2
    sqrd = math.sqrt(sum_square)
    norm_list_test.append(sqrd)       
   
normed_m_test = []   
for i in range(len(strp_nb_test)):
    if all(v == 0 for v in m_test[i]):
        normed = m_test[i]
    else:
        normed = [x / float(norm_list_test[i]) for x in m_test[i]]
    normed_m_test.append(normed)   


In [49]:
########part f########
from sklearn import metrics
from sklearn.linear_model import LogisticRegression

X_train = normed_m
y_train = [sub[-1] for sub in training]
y_test = [sub[-1] for sub in testing]
logreg = LogisticRegression()
logreg.fit(X_train,y_train)

y_pred=logreg.predict(normed_m_test)
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


[[253  47]
 [ 69 231]]
Accuracy: 0.8066666666666666


In [58]:
def find_idx(a,N):
    return np.argsort(a)[::-1][:N]

In [61]:
parameters = logreg.coef_
coef = []
for item in parameters[0]:
    coef.append(item)

absolute_value =  [abs(ele) for ele in coef]
important_idx = find_idx(absolute_value, 20)
for nb in important_idx:
    print(ft_vct[nb])

great
bad
love
excellent
nice
poor
delicious
amaze
best
fantastic
terrible
good
didnt
awesome
waste
suck
awful
well
price
wonderful


In [109]:
#########repeat with a Bernoulli naive bayes classifier#########
from sklearn.naive_bayes import BernoulliNB

X_train = normed_m
y_train = [sub[-1] for sub in training]
y_test = [sub[-1] for sub in testing]
model = BernoulliNB()
model.fit(X_train,y_train)

y_pred = model.predict(normed_m_test)
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))



[[260  40]
 [ 70 230]]
Accuracy: 0.8166666666666667


In [110]:
parameters = model.coef_
coef = []
for item in parameters[0]:
    coef.append(item)

absolute_value =  [abs(ele) for ele in coef]
important_idx = find_idx(absolute_value, 20)
for nb in important_idx:
    print(ft_vct[nb])

acceptable
periodically
echo
warranty
receipt
linksys
refurb
snug
heavyit
utter
visor
tungsten
e2
sin
industrial
track
randomly
admins
tone
chinese


In [71]:
#########part g for (d)#########
pieces = []
for i in range(len(training_tmp)):
    s = training_tmp[i]
    s1 = s.lower()
    s2 = s1.translate(str.maketrans('', '', string.punctuation))
    s3 = s2.split( )
    pieces.append(s3)
   
lemmatized = []  
for i in range(len(pieces)):
    t = []
    t1 = pieces[i]
    for wd in t1:
        t2 = lemmatize(wd)
        t.append(t2)
    lemmatized.append(t)       
    
del_number = []
for i in range(len(lemmatized)):
    u = []
    u1 = lemmatized[i]
    for wd in u1:
        check_nb = wd.isdigit()
        if check_nb is False:
            u.append(wd)      
    del_number.append(u)
########################################################
pieces_test = []
for i in range(len(testing_tmp)):
    s = testing_tmp[i]
    s1 = s.lower()
    s2 = s1.translate(str.maketrans('', '', string.punctuation))
    s3 = s2.split( )
    pieces_test.append(s3)
   
lemmatized_test = []  
for i in range(len(pieces_test)):
    t = []
    t1 = pieces_test[i]
    for wd in t1:
        t2 = lemmatize(wd)
        t.append(t2)
    lemmatized_test.append(t)       
    
del_number_test = []
for i in range(len(lemmatized_test)):
    u = []
    u1 = lemmatized_test[i]
    for wd in u1:
        check_nb = wd.isdigit()
        if check_nb is False:
            u.append(wd)      
    del_number_test.append(u)


In [70]:
def get2gram(sentence):
    my2gram = zip(sentence,sentence[1:])
    res = [' '.join(gram) for gram in my2gram]
    return res

In [75]:
train2gram = []
ft2gram = []
test2gram = []

for i in range(len(del_number)):
    tmp = get2gram(del_number[i])
    train2gram.append(tmp)
    for item in tmp:
        if item not in ft2gram:
            ft2gram.append(item)
    
for i in range(len(del_number_test)):
    tmp = get2gram(del_number_test[i])
    test2gram.append(tmp)    
    
m2gram = [[0 for j in range(len(ft2gram))] for i in range(len(train2gram))]   
m2gram_test = [[0 for j in range(len(ft2gram))] for i in range(len(test2gram))]

for i in range(len(train2gram)):
    y = train2gram[i]
    for item in y:
        idx = ft2gram.index(item)
        ct = y.count(item)
        m2gram[i][idx] = ct

for i in range(len(test2gram)):
    y = test2gram[i]
    for item in y:
        if item in ft2gram:
            idx = ft2gram.index(item)
            ct = y.count(item)
            m2gram_test[i][idx] = ct

   

In [112]:
print(m2gram[20])
print(m2gram[20].count(1))
print(m2gram[21])
print(m2gram[21].count(1))
print(len(ft2gram))

[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [79]:
#########part g for (e)#########
norm_2gram = []
for i in range(len(train2gram)):
    sum_square = 0
    for j in range(len(ft2gram)):
        sum_square = sum_square + (m2gram[i][j])**2
    sqrd = math.sqrt(sum_square)
    norm_2gram.append(sqrd)

normed2gram = []   
for i in range(len(train2gram)):
    if all(v == 0 for v in m2gram[i]):
        normed = m2gram[i]
    else:
        normed = [x / float(norm_2gram[i]) for x in m2gram[i]]
    normed2gram.append(normed)    
              
    
norm_2gram_test = []
for i in range(len(test2gram)):
    sum_square = 0
    for j in range(len(ft2gram)):
        sum_square = sum_square + (m2gram_test[i][j])**2
    sqrd = math.sqrt(sum_square)
    norm_2gram_test.append(sqrd)       
   
normed2gram_test = []   
for i in range(len(test2gram)):
    if all(v == 0 for v in m2gram_test[i]):
        normed = m2gram_test[i]
    else:
        normed = [x / float(norm_2gram_test[i]) for x in m2gram_test[i]]
    normed2gram_test.append(normed)   



In [113]:
########part g for (f)########

X_train = normed2gram
y_train = [sub[-1] for sub in training]
y_test = [sub[-1] for sub in testing]
logreg = LogisticRegression()
logreg.fit(X_train,y_train)

y_pred=logreg.predict(normed2gram_test)
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


[[231  69]
 [ 97 203]]
Accuracy: 0.7233333333333334


In [114]:
p2gram = logreg.coef_
coef = []
for item in p2gram[0]:
    coef.append(item)

absolute_value =  [abs(ele) for ele in coef]
important_idx = find_idx(absolute_value, 20)
for nb in important_idx:
    print(ft2gram[nb])

a great
the best
work great
the bad
do not
i love
very good
love the
be very
very disappoint
be not
would not
highly recommend
love this
be great
piece of
i like
and the
be good
not recommend


In [115]:
#########use Bernoulli naive bayes classifier for 2-gram#########

X_train = normed2gram
y_train = [sub[-1] for sub in training]
y_test = [sub[-1] for sub in testing]
model = BernoulliNB()
model.fit(X_train,y_train)

y_pred = model.predict(normed2gram_test)
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


[[204  96]
 [ 55 245]]
Accuracy: 0.7483333333333333


In [116]:
BNpara = model.coef_
coef = []
for item in BNpara[0]:
    coef.append(item)

absolute_value =  [abs(ele) for ele in coef]
important_idx = find_idx(absolute_value, 20)
for nb in important_idx:
    print(ft2gram[nb])

crust be
the boogeyman
impulse of
of selfpreservation
wa leave
leave shatter
shatter from
experience of
good two
to fully
fully recover
movie now
now join
join revenge
revenge of
boogeyman and
a primal
and zombiez
zombiez a
the hellish


In [122]:
########part h########
from scipy.linalg import svd

avg_lst = []
for j in range(len(ft_vct)):
    tot = 0
    for i in range(len(strp_nb)):
        tot = tot + normed_m[i][j]
    avg = tot/len(strp_nb)
    avg_lst.append(avg)

centerd_m = [[0 for j in range(len(ft_vct))] for i in range(len(strp_nb))]   
for j in range(len(ft_vct)):
    for i in range(len(strp_nb)):
        centerd_m[i][j] = normed_m[i][j] - avg_lst[j]          
    
U, sigma, VT = svd(centerd_m)
print(U.shape)
print(sigma.shape)
print(VT.shape)


(2400, 2400)
(2400,)
(3736, 3736)


In [125]:
avg_lst_test = []
for j in range(len(ft_vct)):
    tot = 0
    for i in range(len(strp_nb_test)):
        tot = tot + normed_m_test[i][j]
    avg = tot/len(strp_nb_test)
    avg_lst_test.append(avg)

centerd_m_test = [[0 for j in range(len(ft_vct))] for i in range(len(strp_nb_test))]   
for j in range(len(ft_vct)):
    for i in range(len(strp_nb_test)):
        centerd_m_test[i][j] = normed_m_test[i][j] - avg_lst_test[j]          
    

In [126]:
def dim_reduce(mtr, d):
    
    turn_mtr = np.array(mtr)
    my_lst = [] 
    
    for p in range(turn_mtr.shape[0]):
        lst = []
        for k in range(d):
            temp_x = np.array(turn_mtr[p,:])
            temp_v = np.array(VT[k,:])
            dot_pd = np.dot(temp_x,temp_v)
            lst.append(dot_pd)
        my_lst.append(lst) 
    f = np.array(my_lst, dtype=float)   
    
    return f
  

In [127]:
to10dim = dim_reduce(centerd_m, 10)

In [128]:
to10dim_test = dim_reduce(centerd_m_test, 10)

In [143]:
#########logistic regrssion for 10-d##########
X_train = to10dim
y_train = [sub[-1] for sub in training]
y_test = [sub[-1] for sub in testing]
logreg10 = LogisticRegression()
logreg10.fit(X_train,y_train)

y_pred=logreg10.predict(to10dim_test)
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


[[229  71]
 [151 149]]
Accuracy: 0.63


In [144]:
##########logistic regression weighted vector for 10-dim########
p10dim = logreg10.coef_
coef = []
for item in p10dim[0]:
    coef.append(item)

absolute_value =  [abs(ele) for ele in coef]
important_idx = find_idx(absolute_value, 5)
for nb in important_idx:
    print(ft_vct[nb])

good
nasty
get
want
tasty


In [147]:
##########naive bayes for 10-dim##########
X_train = to10dim
y_train = [sub[-1] for sub in training]
y_test = [sub[-1] for sub in testing]
NBmodel10 = BernoulliNB()
NBmodel10.fit(X_train,y_train)

y_pred=NBmodel10.predict(to10dim_test)
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[[210  90]
 [161 139]]
Accuracy: 0.5816666666666667


In [148]:
##########naive bayes weighted vector for 10-dim########
NB10dim = NBmodel10.coef_
coef = []
for item in NB10dim[0]:
    coef.append(item)

absolute_value =  [abs(ele) for ele in coef]
important_idx = find_idx(absolute_value, 5)
for nb in important_idx:
    print(ft_vct[nb])

texture
nasty
good
angry
want


In [149]:
to50dim = dim_reduce(centerd_m, 50)

In [150]:
to50dim_test = dim_reduce(centerd_m_test, 50)

In [152]:
#########logistic regrssion for 50-d##########
X_train = to50dim
y_train = [sub[-1] for sub in training]
y_test = [sub[-1] for sub in testing]
logreg50 = LogisticRegression()
logreg50.fit(X_train,y_train)

y_pred=logreg50.predict(to50dim_test)
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


[[233  67]
 [134 166]]
Accuracy: 0.665


In [154]:
##########logistic regression weighted vector for 50-dim########
p50dim = logreg50.coef_
coef = []
for item in p50dim[0]:
    coef.append(item)

absolute_value =  [abs(ele) for ele in coef]
important_idx = find_idx(absolute_value, 5)
for nb in important_idx:
    print(ft_vct[nb])

good
wayyy
nasty
taste
human


In [155]:
##########naive bayes for 50-dim##########
X_train = to50dim
y_train = [sub[-1] for sub in training]
y_test = [sub[-1] for sub in testing]
NBmodel50 = BernoulliNB()
NBmodel50.fit(X_train,y_train)

y_pred=NBmodel50.predict(to50dim_test)
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[[201  99]
 [131 169]]
Accuracy: 0.6166666666666667


In [156]:
##########naive bayes weighted vector for 50-dim########
NB50dim = NBmodel50.coef_
coef = []
for item in NB50dim[0]:
    coef.append(item)

absolute_value =  [abs(ele) for ele in coef]
important_idx = find_idx(absolute_value, 5)
for nb in important_idx:
    print(ft_vct[nb])

tell
texture
nasty
good
honeslty


In [157]:
to100dim = dim_reduce(centerd_m, 100)

In [158]:
to100dim_test = dim_reduce(centerd_m_test, 100)

In [159]:
#########logistic regrssion for 100-d##########
X_train = to100dim
y_train = [sub[-1] for sub in training]
y_test = [sub[-1] for sub in testing]
logreg100 = LogisticRegression()
logreg100.fit(X_train,y_train)

y_pred=logreg100.predict(to100dim_test)
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[[235  65]
 [103 197]]
Accuracy: 0.72


In [161]:
##########logistic regression weighted vector for 100-dim########
p100dim = logreg100.coef_
coef = []
for item in p100dim[0]:
    coef.append(item)

absolute_value =  [abs(ele) for ele in coef]
important_idx = find_idx(absolute_value, 5)
for nb in important_idx:
    print(ft_vct[nb])

good
wayyy
nasty
taste
human


In [162]:
#########naive bayes for 100-dim##########
X_train = to100dim
y_train = [sub[-1] for sub in training]
y_test = [sub[-1] for sub in testing]
NBmodel100 = BernoulliNB()
NBmodel100.fit(X_train,y_train)

y_pred=NBmodel100.predict(to100dim_test)
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[[197 103]
 [124 176]]
Accuracy: 0.6216666666666667


In [163]:
##########naive bayes weighted vector for 100-dim########
NB100dim = NBmodel100.coef_
coef = []
for item in NB100dim[0]:
    coef.append(item)

absolute_value =  [abs(ele) for ele in coef]
important_idx = find_idx(absolute_value, 5)
for nb in important_idx:
    print(ft_vct[nb])

tell
texture
nasty
good
honeslty


In [164]:
########part h for (g)########

avg2gram = []
for j in range(len(ft2gram)):
    tot = 0
    for i in range(len(train2gram)):
        tot = tot + normed2gram[i][j]
    avg = tot/len(train2gram)
    avg2gram.append(avg)

ctd_m2gram = m2gram = [[0 for j in range(len(ft2gram))] for i in range(len(train2gram))]    

for j in range(len(ft2gram)):
    for i in range(len(train2gram)):
        ctd_m2gram[i][j] = normed2gram[i][j] - avg2gram[j]          
    
tomU, tomsigma, tomVT = svd(ctd_m2gram)
print(tomU.shape)
print(tomsigma.shape)
print(tomVT.shape)


(2400, 2400)
(2400,)
(15714, 15714)


In [165]:

avg2gram_test = []
for j in range(len(ft2gram)):
    tot = 0
    for i in range(len(test2gram)):
        tot = tot + normed2gram_test[i][j]
    avg = tot/len(test2gram)
    avg2gram_test.append(avg)

ctd_m2gram_test = [[0 for j in range(len(ft2gram))] for i in range(len(test2gram))]   

for j in range(len(ft2gram)):
    for i in range(len(test2gram)):
        ctd_m2gram_test[i][j] = normed2gram_test[i][j] - avg2gram_test[j]          
    

In [166]:
def dim_reduce_2g(mtr, d):
    
    turn_mtr = np.array(mtr)
    my_lst = [] 
    
    for p in range(turn_mtr.shape[0]):
        lst = []
        for k in range(d):
            temp_x = np.array(turn_mtr[p,:])
            temp_v = np.array(tomVT[k,:])
            dot_pd = np.dot(temp_x,temp_v)
            lst.append(dot_pd)
        my_lst.append(lst) 
    f = np.array(my_lst, dtype=float)   
    
    return f

In [167]:
to10dim_2g = dim_reduce_2g(ctd_m2gram, 10)

In [168]:
to10dim_2g_test = dim_reduce_2g(ctd_m2gram_test, 10)

In [169]:
#########2-gram logistic regrssion for 10-d##########
X_train = to10dim_2g
y_train = [sub[-1] for sub in training]
y_test = [sub[-1] for sub in testing]
lr10_2g = LogisticRegression()
lr10_2g.fit(X_train,y_train)

y_pred=lr10_2g.predict(to10dim_2g_test)
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[[237  63]
 [205  95]]
Accuracy: 0.5533333333333333


In [171]:
##########2-gram logistic regression weighted vector for 10-dim########
p10dim_2g = lr10_2g.coef_
coef = []
for item in p10dim_2g[0]:
    coef.append(item)

absolute_value =  [abs(ele) for ele in coef]
important_idx = find_idx(absolute_value, 5)
for nb in important_idx:
    print(ft2gram[nb])

the texture
crust be
and the
wa just
tasty and


In [172]:
#########2-gram naive bayes for 10-dim##########
X_train = to10dim_2g
y_train = [sub[-1] for sub in training]
y_test = [sub[-1] for sub in testing]
NBmodel10d2g = BernoulliNB()
NBmodel10d2g.fit(X_train,y_train)

y_pred=NBmodel10d2g.predict(to10dim_2g_test)
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[[136 164]
 [ 91 209]]
Accuracy: 0.575


In [173]:
##########2-gram naive bayes weighted vector for 10-dim########
p10d2g = NBmodel10d2g.coef_
coef = []
for item in p10d2g[0]:
    coef.append(item)

absolute_value =  [abs(ele) for ele in coef]
important_idx = find_idx(absolute_value, 5)
for nb in important_idx:
    print(ft2gram[nb])

be not
not good
crust be
wa just
the texture


In [174]:
to50dim_2g = dim_reduce_2g(ctd_m2gram, 50)

In [175]:
to50dim_2g_test = dim_reduce_2g(ctd_m2gram_test, 50)

In [176]:
#########2-gram logistic regrssion for 50-d##########
X_train = to50dim_2g
y_train = [sub[-1] for sub in training]
y_test = [sub[-1] for sub in testing]
lr50_2g = LogisticRegression()
lr50_2g.fit(X_train,y_train)

y_pred=lr50_2g.predict(to50dim_2g_test)
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[[222  78]
 [149 151]]
Accuracy: 0.6216666666666667


In [177]:
##########2-gram logistic regression weighted vector for 50-dim########
p50dim_2g = lr50_2g.coef_
coef = []
for item in p50dim_2g[0]:
    coef.append(item)

absolute_value =  [abs(ele) for ele in coef]
important_idx = find_idx(absolute_value, 5)
for nb in important_idx:
    print(ft2gram[nb])

i be
the texture
keep under
tell they
angry and


In [178]:
#########2-gram naive bayes for 50-dim##########
X_train = to50dim_2g
y_train = [sub[-1] for sub in training]
y_test = [sub[-1] for sub in testing]
NBmodel50d2g = BernoulliNB()
NBmodel50d2g.fit(X_train,y_train)

y_pred=NBmodel50d2g.predict(to50dim_2g_test)
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[[168 132]
 [114 186]]
Accuracy: 0.59


In [179]:
##########2-gram naive bayes weighted vector for 50-dim########
p50d2g = NBmodel50d2g.coef_
coef = []
for item in p50d2g[0]:
    coef.append(item)

absolute_value =  [abs(ele) for ele in coef]
important_idx = find_idx(absolute_value, 5)
for nb in important_idx:
    print(ft2gram[nb])

be not
not good
crust be
wa just
the texture


In [180]:
to100dim_2g = dim_reduce_2g(ctd_m2gram, 100)

In [181]:
to100dim_2g_test = dim_reduce_2g(ctd_m2gram_test, 100)

In [182]:
#########2-gram logistic regrssion for 100-d##########
X_train = to100dim_2g
y_train = [sub[-1] for sub in training]
y_test = [sub[-1] for sub in testing]
lr100_2g = LogisticRegression()
lr100_2g.fit(X_train,y_train)

y_pred=lr100_2g.predict(to100dim_2g_test)
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[[214  86]
 [130 170]]
Accuracy: 0.64


In [183]:
##########2-gram logistic regression weighted vector for 100-dim########
p100dim_2g = lr100_2g.coef_
coef = []
for item in p100dim_2g[0]:
    coef.append(item)

absolute_value =  [abs(ele) for ele in coef]
important_idx = find_idx(absolute_value, 5)
for nb in important_idx:
    print(ft2gram[nb])

i be
the texture
keep under
tell they
angry and


In [184]:
#########2-gram naive bayes for 100-dim##########
X_train = to100dim_2g
y_train = [sub[-1] for sub in training]
y_test = [sub[-1] for sub in testing]
NBmodel100d2g = BernoulliNB()
NBmodel100d2g.fit(X_train,y_train)

y_pred=NBmodel100d2g.predict(to100dim_2g_test)
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[[162 138]
 [ 92 208]]
Accuracy: 0.6166666666666667


In [185]:
##########2-gram naive bayes weighted vector for 100-dim########
p100d2g = NBmodel100d2g.coef_
coef = []
for item in p100d2g[0]:
    coef.append(item)

absolute_value =  [abs(ele) for ele in coef]
important_idx = find_idx(absolute_value, 5)
for nb in important_idx:
    print(ft2gram[nb])

be not
not good
crust be
wa just
the texture
